### ISSUE TITLE
product detail enhancements

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#1258]
Planning notes for product detail enhancements
# Upgradability / customization
- [x] more components ;-)
- [x] move remaining inline edit elements to sidebar
- [ ] enable/disable per component
- [x] reactionTemplates
- [x] products without variants #500
- [ ] multi variant #367 #659
- [x] select product type (simple,etc) to apply schema
  - [ ] where type=simple and component is visible and lang = current lang
  - [ ] type = choose the product layout
# Functionality
- [x] revisions
- [ ] ui customization per product
- [x] workflow publishing approval  (staging of changes) #1178 
- [ ] i18n language versioning
- [ ] inheritance management (#150)
# Tags
- [ ] multiple languages
- [ ] default to base shop version
# Admin
- [ ] product list view #465 #300
# Priorities
- [x] component / edit element UX
- [x] admin panel UX (closing)
- [x] publishing workflow
- [ ] visibility date

**Comment by mikemurray** [comment]
Needs more tickets to break up these tasks into smaller chunks.

**Comment by aaronjudd** [comment]
Closing in favor of various marketplace PDP / react component issues.
