### ISSUE TITLE
[PDP] Revisions UX updates

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#1455]
Implement remaining UX update for https://github.com/reactioncommerce/reaction/pull/1356
- [x] move revisions dashboard card into Catalog card  (and i18n update) **PR** #1544
- [x] updated "Loading" spinner (should be universal) **PR** #1471
- [x] UX move delete button to same row (shouldn't need row to be active to delete)
- [x] UX to collapse accordions, focus edit target and open **PR** #1569
- [x]  Reimplement a confirmation UX when updating inputs (formerly turned green and fade on success) **PR** #1558
- [x] Ensure all inputs have placeholders **PR** #1472, #1542

**Comment by zenweasel** [comment]
- [ ] Some fields like details and manufacturer and not submitted when pressing enter while others like Tag are. Probably any field that makes sense to be submitted by enter should be.

**Comment by aaronjudd** [comment]
#1471 did not close #1455 (loading indicator for PDP).  I am still seeing the text loader.

![example-product_and_reactioncommerce_reaction_and_inbox__14_759_messages__3_unread_](https://cloud.githubusercontent.com/assets/439959/20197926/c36085ca-a756-11e6-9f59-28f6869adeda.png)

**Comment by mikemurray** [comment]
Different loading issue, as this one is with reaction layout.
