### ISSUE TITLE
AvaTax TaxCodes and UI Certification

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#1793]
Additional UI and functionality is needed to have our AvaTax module be "certified".

Some are additional settings, and will need UI in the dashboard settings.

**Implementation requirements are here:** 
http://developer.avalara.com/avatax/testing-your-integration/

Integration checklist for Functional Review
http://developer.avalara.com/avatax/certification/
 
Use Case for handling Exemptions
http://developer.avalara.com/avatax/handling-tax-exempt-customers/
 
Using the RESTv2 API, there are two http headers we need to pass:
- X-Avalara-Client :  This is a string in the format '(app name); (app version); (library name); (library version); (machine name)'
- X-Avalara-UID: xxxxxxxxxx
 
Swagger (AvaTax API reference)
https://rest.avatax.com/swagger/ui/index.html
 
These endpoints can be used to retrieve TaxCodes,etc. 
TaxCodes will need to be stored on product, see #1699 
Line Item calculation is required (should already be wired this way).

Testing can be validated here: http://developer.avalara.com/avatax/self-test/

Future - Developer Blog post on Landed Cost using RESTv2 API
http://developer.avalara.com/blog/2016/10/13/landedcost-with-rest-v2/

**Comment by aaronjudd** [comment]
Example certification settings:
![screenshot_2_6_17__5_00_pm](https://cloud.githubusercontent.com/assets/439959/22678198/33d9d270-ecad-11e6-92b3-0a380f85803e.png)

**Comment by zenweasel** [comment]
For us the Tax codes for Shipping/Handling should probably go in the Avalara tax settings panel

**Comment by zenweasel** [comment]
Some Todo items here:

- [ ] Add a "Tax Exempt" field/checkbox to the Account record
- [ ] Add a "Tax Description" field to Products (can be added to what @kieha is doing)
- [ ] Record a **per item** tax rate in the cart/order
- [ ] Reflect tax code/tax rate **per item** in the order management screens
- [ ] Returns in Avalara are done per line items, but now we just do "refunds" on the whole order. How do we handle this? Do we need to create a new interface for return/refund line items?
- [ ] Ensure that discounts are taken into account when recording taxes

**Comment by zenweasel** [comment]
Current audit self-test results

![developer___integration_self-test](https://cloud.githubusercontent.com/assets/72819/23539593/35201ae0-0017-11e7-976c-342d7d74bbf6.png)

**Comment by zenweasel** [comment]
We had the compliance audit today and here were the issues that came up:

### Compliance Issues

1. **Biggest Issue** Breaking out quantities into individual items is going to cause some issues with Avalara's limits on order sizes. #2102 
1. We need to warn but not stop customers from proceeding with an order if the address fails complete address validation. (do we need to record the fact that it didn't validate?)
1. The Order ID displayed in the admin panel and the Order ID being transmitted to Avalara is not the same so it's hard to cross-reference the two.
1. "Customer Usage Type" doesn't allow you to set a custom value. #2101 

Not blockers for compliance but things on the horizon:

1. Location code for Retail locations (Evereve?)
1. "Tax Included" for VAT retailers

**Comment by zenweasel** [comment]
Ok, so the "biggest issue" wasn't the biggest issue, address validation is. But once #2104 is completed we should be good to go. Moving out to 1.2

**Comment by zenweasel** [comment]
We are certified. Closing
