### ISSUE TITLE
[EPIC] Upgrade dashboard panels to use React components

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction#1835]
Fix behavior and standardize card component with switch related to:
https://github.com/reactioncommerce/reaction/issues/1795

Expected behavior. When you toggle it on to activate it will open. When you click on the bar or arrow it closes and opens without activating or deactivating the switch. When you deactivate the switch it close the card as well. 

Two more notes: 
<img width="458" alt="card-cleanup" src="https://cloud.githubusercontent.com/assets/20409254/22988831/4f642de4-f368-11e6-96d1-a32224adb032.png">

**Comment by rymorgan** [comment]
![sidebar card with switch](https://cloud.githubusercontent.com/assets/20409254/22988467/10709ce0-f367-11e6-9114-6b065dd2d0c3.png)

**Comment by kieckhafer** [comment]
List of Dashboard Cards that should be upgraded to React:

- [ ] Orders - Not touching at this time

- [ ] Analytics - Convert to React. Should be combined with Analytics Settings, and completely moved into the settings section. - TICKET NEEDED

- [ ] Accounts - Everything - TICKET NEEDED

- [ ] Localization - #1797 

- [ ] Shop - Everything - TICKET NEEDED

- [ ] Email - #1836 

- [ ] Payment - Everything - TICKET NEEDED

- [ ] Shipping - Everything - TICKET NEEDED

- [ ] Catalog - Everything - TICKET NEEDED

- [ ] Template - Put inside React Card, possibly make medium sized? - TICKET NEEDED

- [ ] Reaction Connect - Everything - This will be upgraded with LaunchDock? - TICKET NEEDED

- [ ] Search - Put in React Card, form? - TICKET NEEDED

- [ ] SMS - #1836 

- [ ] Social - #1854 

- [ ] Taxes - Everything - TICKET NEEDED

**Comment by rymorgan** [comment]
closed in favor of #2040

**Comment by rymorgan** [comment]
closed in favor of #2040
