### ISSUE TITLE
React + SSR conversion of remaining components

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#2040]
# React + SSR

This epic is meant to track the conversion of all customer / admin facing components, layouts, templates to React. This means no more Blaze wrappers around any react component, and no Blaze components at any point in the React layout tree. All react all the time.

**Keep in mind, for SSR to work, no react component may access `document` or `window` while being rendered server-side. If you need them, you'll need to check if they exists before trying to access.**

**Below List in ordered by approximate priority**

## Router

- [x] #2049 Must attempt render a react layout first, fallback to blaze until the conversion is complete. (PR #2123) @mikemurray
- [x] #2049 `ReactionLayout` should support react components / layouts if one is registered (PR #2123) @mikemurray
- [ ] **BLOCKED** Enable SSR support after everything is react @mikemurray
- [x] FlowRouter -> React Router (PR #2123) @mikemurray

## Layout

- [x] Separate `coreAdminLayout` from `coreLayout` (PR #2123) @mikemurray
- [x] #2049 Layout should use the `React` version of ReactionLayout, used in the PDP page @mikemurray

## Navigation bar

- [x] #2041 Navigation bar itself 
- [x] #2042 Cart drawer & checkout popup when adding to cart @andela-aatanda
- [x] #2043 Tag navigation (already has a react version, for the tag component / `imports/plugins/core/ui/core/client/compnents/tags/ & imports/plugins/core/ui/core/client/containers/tagListContainer) @kieckhafer
- [x] #2044 Alerts, Language and other dropdowns

## Product Grid

- [x] #2050 Grid layout & items

## Search

- [x] #2051 Search modal and all subviews (`ui-search` package)
- [x] #2050 Grid layout & items for products (needs to use the exact same component as the grid)

## Checkout

- [ ] #2052 Checkout layout
- [ ] #2052 Checkout progress
- [ ] #2055 Login (shared with login dropdown and 403 page)
- [ ] #2053 & #2052 Address book, (is also used in user profile)
- [ ] #2052 Shipping options
- [ ] #2052 or #2042 Summary
- [ ] #2052 Payment options

## Product Detail

- [x] #2032 PDP Variant admin view (PR #2086) @kieha 

## Orders

- [x] #2045 Orders summary card (PR #2105) @joykare 

## Admin

- [x] Action view should render a react component if one exists. (DONE, if you register a react component with the same name you use for `template` while opening an ActionView, it will use the react component before falling back to a blaze template.)
- [x] Orders - Convert and update UX
- [ ] Analytics - Convert to React. Should be combined with Analytics Settings, and completely moved into the settings section. - TICKET NEEDED
- [x] Accounts - Everything - TICKET NEEDED
- [x] Localization - #1797 & #1773 
- [ ] Shop - Everything - TICKET NEEDED
- [x] Email - #1836 
- [ ] Payment - Everything - TICKET NEEDED
- [ ] Shipping - Everything - TICKET NEEDED
- [ ] Catalog - Everything - TICKET NEEDED
- [x] Template - Put inside React Card, possibly make medium sized? - TICKET NEEDED
- [ ] Reaction Connect - Everything - This will be upgraded with LaunchDock? - TICKET NEEDED
- [ ] Shop- #3715
- [ ] Search - Put in React Card, form? #3325, #3424
- [ ] Shopify Import- #3187
- [x] SMS - #1836 
- [x] Social - #1854 
- [ ] Taxes - Everything - TICKET NEEDED

**Comment by aaronjudd** [comment]
Issue moved to [reactioncommerce/reaction-feature-requests #7](https://github.com/reactioncommerce/reaction-feature-requests/issues/7) via [**ZenHub**](https://www.zenhub.com/)
