### ISSUE TITLE
Orders UIX Updates

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction#2046]
Epic for UIX Order Updates. 

Issues: 
- [x] Summary card update #2045
- [x] Summary card update #2047
- [ ] Large View Redesign #2150
- [ ] List View #2151
- [ ] Search/Filtering #2152
- [ ] Shipping Flow #2153
- [ ] Capture Payment Flow #2154
- [ ] Bulk Actions #2155
- [ ] Update components on Orders  https://github.com/reactioncommerce/reaction/issues/2111
- [ ] Line Item Editing (Still working on requirements and design)

**Comment by rymorgan** [comment]
Closing in favor of all the Marketplace Orders Issues.
