### ISSUE TITLE
[EPIC][WIP] Marketplace Orders

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#2219]
# Marketplace Orders and Fulfillment
This should probably be split into multiple epics, but is a decent place to gather knowledge for now. Will probably become `Marketplace Orders` and  `Marketplace Fulfillment` at a minimum. Suggestions welcome for how to split this up.

# Tasks
### Completed Order
-   [ ] Completed order should break items out by vendor (#2308)
-   [ ] Completed order should break items out by shipment (#2309)
-   [ ] Unprocessed items in a completed order that has not been captured should permit user initiated cancellation (#2310) **[Phase 2]**
-   [ ] Unshipped items in a completed order should show estimated arrival date and time (#2311)
-   [ ] Unshipped items in a completed order should show any exceptions or delays associated with the order processing (#2312) **[Phase 2]**
-   [ ] Order complete screen should show customer what state each partial of her order is in.

### Order Tracking
-   [ ] Fulfilled shipments with a Shippo integration should create a subscription to Shippo tracking updates (#2318)
-   [ ] Orders with tracking subscriptions should trigger an EventHook when a shipping exception has occurred (#2320)
-   [ ] Order Managers should be able to track an order from the order details screen (#2321)

### Order Followup
-   [ ] After an order has been delivered, an order followup email and notification should be sent (#2351)

### Orders Dashboard
-   [ ] Order managers should be able to see a risk evaluation for an order (#2322) (WIP PR #2744)
-   [x] Order managers should be able to toggle between list and detail view in the order Dashboard (#2323)
-   [ ] Order managers should be able to export orders via CSV (#2324)
-   [x] Order managers should be able to select orders from the order list (#2325)

### Order Filtering
-   [x] Order managers should be able to filter the orders list by status (#2357)
-   [x] Order managers should be able to filter the orders list by created date (#2359)
-   [x] Order managers should be able to filter the orders list by shipping status (#2906)
-   [ ] Order managers should be able to filter the orders list by shipping method (#2360)
-   [ ] Order managers should be able to filter the orders list by billing or shipping location (#2361)
-   [x] Order managers should be able to clear all active filters in one click (#2358)

### Order Sorting
-   [ ] Order managers should be able to sort the orders list by column (#2363)

### Order Searching
-   [x] ~Order managers should be able to fuzzy search orders by orderId (#2353)~
-   [x] ~Order managers should be able to fuzzy search orders by customer name, email, or phone number (#2354)~
-   [x] ~Order managers should be able to fuzzy search orders by product title, variant title/label, or option title/label contained within that order (#2355)~

### Bulk Order Actions
-   [x] Order managers should be able to set an order or multiple orders to a specific status (#2341)
-   [ ] Order managers should be able to print labels in bulk (#2342)
-   [ ] Order managers should be able to print invoices / pick sheets in bulk (#2343)

### Order Splitting Logic
-   [ ] Order UI should be filtered and "split" based on role (#2367)

### Order Returns and Refunds
-   [ ] Generate and send RMA and return instructions to customer (#2373) **[Phase 2]**
-   [ ] Refunding returned orders (#2374)
-   [ ] Refund shipping for an order (#2376)
-   [x] Refund a line item or a quantity of a line item (#2377)
-   [ ] Refund an order by adding a discount to a completed order (#2378)

### Order Management
-   [ ] Copy order link to the clipboard (#2379)
-   [ ] Orders should be sharable via Slack (#2381)
-   [ ] Vendors should be able to issue refunds for their part of an order [Should they? Discussion?] [Needs Ticket] **[Phase 2]**
-   [x] Before capturing payment, order managers should be able to cancel an order. (#1238)
-   [ ] Cancel a line item from an order (#2382)
-   [ ] Display split view for orders that have multiple shipments or vendors (#2383)
-   [ ] Split shipments that are partially picked in one click (#2384)

### Shop Management
-   [ ] Store Managers should be able to configure new orders to be posted to a specific Slack channel (#2346)
-   [ ] Shop owners should be able to set their order processing time in business days (#2345)

--- Everything below this line is [Phase 2] ---

### Reviews
-   [ ] As a shopper, after completing a checkout I should be able to review a vendor
-   [ ] As a shopper, for each unique item I order, I should be able to leave a product review
-   [ ] When leaving a review, I should be able to attach images.

### Expiration and Aging
-   [ ] Handling orders with expired payment authorization (#2347)
-   [ ] Show warning when payment authorization is about to expire (#2352)
-   [ ] Orders to be shipped today should be labeled DUE or LATE (#2344)

### Shipping
-   [ ] Flat Rate shipping should support per item shipping fee
-   [ ] Flat Rate shipping should support item specific shipping fee

### General Order Related Tasks
-   [ ] Line Item Returns (#1849)
-   [ ] Shipping should be taxable (#1941)

### UIX & Component Tasks
-   [ ] Section headers inside orders panel should be collapsable (#2161)
-   [x] Action View throws error and breaks rendering (#2136)
-   [x] Show Order ID on order completed screen (#1882)
-   [x] Orders should be searchable (#1487)

### Marketplace Fulfillment Tasks
-   [ ] Shop Order managers should be able to fulfill partial orders with items they are the fulfillment provider for.
-   [ ] Order Partials with 3PL fulfillment providers should have API endpoints for receiving order updates
-   [ ] Order partials with 3PL fulfillment providers should subscribe to order update webhooks

#### Vendor notes
A vendor can cancel multiple parts of their partial order, but if at any point all items from their partial order are cancelled, their partial order should be considered closed in relation to the full order.

### Order and Order Item States
Each item carries it's own state independent of the order

##### New 
-   Web
-   POS (soon)
-   Phone (soon)

##### Processing
-   Ready 
-   Picking 
-   Picked 
-   Packing 
-   Packed 
-   Labeled (Ready For Shipping / Pickup)

##### Shipped 
-   In Transit 
    -   Last Location
-   Exception
    -   Delay (Weather, Error)
    -   Lost
    -   Damaged
    -   Redirected

##### Delivered / Completed
-   Delivered [Location (front door, porch, etc)

##### Returning 
-   Return Requested
-   Refunded, awaiting return
-   Return Shipped
-   Return Exception
-   Return Delivered

##### Cancelled
-   Cancelled By Customer
-   Cancelled By Vendor
-   Partially Cancelled

Additional statuses for order items
-   Backordered
-   Out of stock
-   

### Order Processing Analytics
-   Average order processing time
-   Number of LATE Orders in the last 30/60/90 days
-   Number of DUE orders today
-   For each picker, avg time to pick and pack an order
-   For each order, estimated fulfillment time
-   NPS score (30, 90, 365, all time)
-   Marketplace shops with LATE orders
-   Marketplace shops with high average order processing time
-   Marketplace shops with below average NPS
-   Top performing Marketplace Shops processing orders quickly
-   Top performing individual pickers processing orders quickly

**Comment by vanloc0301** [comment]
Can you add pull request for this feature?

**Comment by spencern** [comment]
hi @vanloc0301 - This feature is under development and you can follow along here and in the `marketplace` chat room.

**Comment by vanloc0301** [comment]
that's cool @spencern . I expect expectations like a review of the customer when they buy success.

**Comment by aldeed** [comment]
The multi-shop aspects of this are done in 2.0.0. The marketplace-specific aspects will not be done because marketplace is no longer a core feature.
