### ISSUE TITLE
Implement UI/UX for accounts admin

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction#2922]
**UX issues**
This is an epic to implement the UI/UX for accounts admin

- [ ] https://github.com/reactioncommerce/reaction/issues/2963 - Properly implement the large accounts view with independently scrollable master and detail panels. 
- [ ] https://github.com/reactioncommerce/reaction/issues/3102 - Accounts admin - clicking header should allow user to edit group
- [ ] https://github.com/reactioncommerce/reaction/issues/3105 - Accounts admin - implement accordion editing for groups 
- [ ] https://github.com/reactioncommerce/reaction/issues/3106 - Accounts admin - toggle all permission on/off
- [ ] https://github.com/reactioncommerce/reaction/issues/3107 - Accounts admin - implement change account owner flow
- [ ] https://github.com/reactioncommerce/reaction/issues/3108 - Accounts admin - ability to edit and reset password for a user 
- [ ] https://github.com/reactioncommerce/reaction/issues/3109 - Accounts admin- fix button placement
- [ ] https://github.com/reactioncommerce/reaction/issues/3110 - Accounts admin - styling
- [ ] https://github.com/reactioncommerce/reaction/issues/3119 - Accounts admin - need a way to search users
- [ ] _Place holder_ - Registered users and guest users (aka customers) need a separate admin panel from the accounts admin
- [ ] _Place holder_ - Need an issue detailing an owner's initial experience (mini-onboarding) for accounts admin. -  https://zpl.io/a3qJqA2

**Comment by rymorgan** [comment]
@spencern I know this is a monster, but accounts does not look fully formed. And is far from client ready. Maybe we can discuss how to break down and prioritize my many UI/UX concerns here.

**Comment by spencern** [comment]
@rymorgan and I discussed this issue on on Thursday and determined that some of these were blocking while other parts may not be. 

Ryan did we end up creating a separate issue for that?

**Comment by rymorgan** [comment]
Here's the issue that is the blocker: https://github.com/reactioncommerce/reaction/issues/2921

See Mike's comments on that issue for more context. I will remove the marketplace label on this permissions UI issue. Post marketplace release we can break this out into multiple issues.

**Comment by rymorgan** [comment]
@spencern Fully converted this issue into an epic. It's 90% designed out, I've also identified a few leftover design tasks.

**Comment by aldeed** [comment]
Moved all linked issues to https://github.com/reactioncommerce/reaction-admin repo
