### ISSUE TITLE
Header navigation Mobile and desktop views. 

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction#3341]
## Problem 
The navigation on mobile has too many items in it and is causing bugs where it doesn't fit on mobile. 

## **Fix**

**Cart**

- [x] Cart bg should snap into a square on mobile. 
- [x] For mobile, the cart icon can shrink to 22px.
- [x] The cart items indicator bg circle  should be made @rui-brand for both  mobile and desktop
- [x] For mobile, the items indicator should overlap the cart icon. 

Cart desktop/tablet
https://app.zeplin.io/project/58af8900737c137280322bd6/screen/5a136340e2e8c516788cbd7e?
![header tablet - signed out](https://user-images.githubusercontent.com/20409254/33106142-a7a745dc-cee5-11e7-948c-d148e4f11d27.png)

Cart mobile signed out
https://app.zeplin.io/project/58af8900737c137280322bd6/screen/5a1363448067bf4ea687d5b7?
![header mobile - signed out](https://user-images.githubusercontent.com/20409254/33106141-a78ecfac-cee5-11e7-9417-6ad974fc06ab.png)

Cart mobile signed in
![header mobile - signed in](https://user-images.githubusercontent.com/20409254/33106140-a775e1ea-cee5-11e7-8e94-45b5b6482b39.png)
https://app.zeplin.io/project/58af8900737c137280322bd6/screen/5a14d860c6c1036037233ae1

**Navigation bar**

**Both**

- [x] When signed out we can use the user icon instead of the language that says “Sign in” 

Cart desktop/tablet
https://app.zeplin.io/project/58af8900737c137280322bd6/screen/5a136340e2e8c516788cbd7e?
![header tablet - signed out](https://user-images.githubusercontent.com/20409254/33106142-a7a745dc-cee5-11e7-948c-d148e4f11d27.png)

Cart mobile signed out
https://app.zeplin.io/project/58af8900737c137280322bd6/screen/5a1363448067bf4ea687d5b7?
![header mobile - signed out](https://user-images.githubusercontent.com/20409254/33106141-a78ecfac-cee5-11e7-9417-6ad974fc06ab.png)

**Mobile**

- [x] Show only search and account
- [x] Account can lose the name and just show the user profile image

Cart mobile signed out
https://app.zeplin.io/project/58af8900737c137280322bd6/screen/5a1363448067bf4ea687d5b7?
![header mobile - signed out](https://user-images.githubusercontent.com/20409254/33106141-a78ecfac-cee5-11e7-9417-6ad974fc06ab.png)

Cart mobile signed in
![header mobile - signed in](https://user-images.githubusercontent.com/20409254/33106140-a775e1ea-cee5-11e7-8e94-45b5b6482b39.png)
https://app.zeplin.io/project/58af8900737c137280322bd6/screen/5a14d860c6c1036037233ae1

**Hamburger menu**

- [ ] Move alerts (bell icon), language selector, and currency selector to hamburger. 

Mobile hamburger menu
https://app.zeplin.io/project/58af8900737c137280322bd6/screen/5a14dabaa317b93f4eb389e3?
![super admin dropdown](https://user-images.githubusercontent.com/20409254/33106293-4e764642-cee6-11e7-88d4-1683773ad3b3.png)

**Desktop/tablet**

Reduce padding between icon buttons in nav
Icon button should be grouped in the upper right

Deskto/tablet navigation 

https://app.zeplin.io/project/58af8900737c137280322bd6/screen/5a136340e2e8c516788cbd7e?
![header tablet - signed out](https://user-images.githubusercontent.com/20409254/33106327-697c1dc2-cee6-11e7-8f8f-3b375ddf1740.png)

**Mobile publish bar **

- [ ] Move the shop switcher navigation to the hamburger menu for mobile 
- [x] Change styles of the shop switcher navigation for mobile and desktop
- [x] If there’s only one shop, we shouldn’t see the shop switcher

Mobile nav with publish bar
https://app.zeplin.io/project/58af8900737c137280322bd6/screen/5a14d860c6c1036037233ae1?
![admin](https://user-images.githubusercontent.com/20409254/33106382-a6c7b6aa-cee6-11e7-8c73-3e797896aef2.png)

**Comment by Derewith** [comment]
Great job but i think we might work by our own to make all of these changes

**Comment by aldeed** [comment]
Resolved in 2.0.0
