### ISSUE TITLE
EPIC: GraphQL API

### ISSUE THREAD

**Issue by ticean** [reactioncommerce/reaction#3878]
# Reaction GraphQL

The [Github GraphQL API documentation][3] has a clear description of GraphQL:

> The GraphQL data query language is:

> * A **[specification][2]**. The spec determines the validity of the schema on the API server. The schema determines the validity of client calls.
> * **Strongly typed.** The schema defines an API's type system and all object relationships.
> * **Introspective.** A client can query the schema for details about the schema.
> * **Hierarchical.** The shape of a GraphQL call mirrors the shape of the JSON data it returns. Nested fields let you query for and receive only the data you specify in a single round trip.
> * **An application layer.** GraphQL is not a storage model or a database query language. The graph refers to graph structures defined in the schema, where nodes define objects and edges define relationships between objects. The API traverses and returns application data based on the schema definitions, independent of how the data is stored.

More background, information, and rationale can be found on the [GraphQL.org website.][4]

## Why GraphQL for Reaction

* **Headless Commerce.** - We aim to provide a commerce available available to any frontend.
* **It's expressive.** GraphQLs expressive query language, reduced round-trips to the server, and realtime data subscriptions offer clear advantages over RESTful APIs and provide parity to Meteor methods and subscriptions. Clients can specify the data shape they need.
* **Performance Improvement.** We're planning to break the client and server into separate codebases to move away from the isomorphic model in Meteor.
* **Even more performance improvement.** We plan to remove Meteor and DDP as core dependencies of the Reaction project.
* **A path to additional backend services.** We'd like to provide a way to deploy additional functionality is not in Reaction core. This can be extracting functionality from Reaction into separate services for performance reasons, or building new functionality into new services. GraphQL will allow us to position these services behind an API gateway.

## Objective

Add a GraphQL gateway to the Reaction project. This API will offer parity with the existing Meteor interfaces and will be a replacement.

We'll run Meteor and GraphQL together for some time with Meteor being deprecated and eventually removed.

#### GraphQL in the Reaction Process

We'll run GraphQL in the Reaction process so that it will ship automatically with Reaction. While the endpoint should be configurable, it will be available in any Reaction instance at `/graphql`.

#### Take Advantage of the GraphQL Model

**TODO**:

* Thinking in graphs
* Is an opportunity to make tweaks to our interface
* Not intended for feature requests/additions

#### GraphQL Resolver as a Thin Layer

GraphQL resolvers in Reaction should be razor thin and should dispatch requests from the client to business logic in the application.

## Reference

* [Introduction to GraphQL][1]
* [GraphQL Spec][2]
* [Example Implementation: Github GraphQL API v4][3]

[1]: http://graphql.org/learn/ "Introduction to GraphQL"
[2]: http://facebook.github.io/graphql/October2016/ "GrqphQL Spec"
[3]: https://developer.github.com/v4/ "GitHub GraphQL API v4"
[4]: http://graphql.org "GraphQL | A query language for your API"

## Tasks

* [x] Figure out how to call out to Meteor methods in resolvers
* [x] Figure out how to create subscriptions for Meteor publications
* [x] Create a list of initial entities that we'll support. eg, Prioritized list.
  * [x] List all Meteor Methods
  * [x] Verify if each method is called (`Meteor.call`)
  * [x] List all Meteor Publications (42 by search), `Meteor.publish()`
  * [x] Verify if each publication is used in subscription
* [x] Prioritize the methods that should be ported to GraphQL.
* [x] Prioritize subscriptions that should be ported to GraphQL.
* [x] Decide if any transformations will be applied to Reaction entity schemas in GraphQL.
* [x] Create GraphQL schema for all Reaction entities.
* [x] Scaffold the GraphQL server into Reaction project
  * [x] GraphQL endpoint
  * [x] GraphiQL playground 
* [x] Demo components by injecting GraphQL frontend components with [replaceComponent](https://docs.reactioncommerce.com/reaction-docs/master/components-api)

**Comment by aldeed** [comment]
The GraphQL API isn't complete yet, but this epic is no longer used for tracking the work.
