### ISSUE TITLE
[EPIC] Jest integration tests to cover full GraphQL API

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction#5310]
## Overview

In preparation for a push to remove the Meteor dependency from the GraphQL API, we would like full integration test coverage of all GraphQL queries and mutations provided by all core and included plugins. This epic issue will serve as the central tracking place for the work necessary to write all missing integration tests.

### Mutations That Have Integration Tests
- addAccountAddressBookEntry
- addOrderFulfillmentGroup
- cancelOrderItem
- moveOrderItems
- publishProductsToCatalog
- splitOrderItem
- updateOrder
- updateOrderFulfillmentGroup
- updateSimpleInventory

### Mutations That Need Integration Tests
- [x] Write a full checkout flow integration test #5518
  - createCart (with items)
  - addCartItems (add more items)
  - reconcileCarts (login flow)
  - removeCartItems
  - setEmailOnAnonymousCart
  - setShippingAddressOnCart
  - updateCartItemsQuantity
  - updateFulfillmentOptionsForGroup
  - selectFulfillmentOptionForGroup
  - availablePaymentMethods
  - placeOrder
---
- [x] addAccountEmailRecord #5643 
- [x] addAccountToGroup #5431 
- [x] addCartItems #5645 
- [x] addTag #5664
- [x] approveOrderPayments #6012 
- [x] captureOrderPayments #6014
- [x] createFlatRateFulfillmentMethod #5967 @trojanh 
- [x] createFlatRateFulfillmentRestriction #5981
- [x] createAccountGroup #5945
- [x] createNavigationItem #5886
- [x] createSurcharge #5937 @trojanh 
- [x] deleteFlatRateFulfillmentMethod  #5966 @trojanh 
- [x] deleteFlatRateFulfillmentRestriction #5981
- [x] deleteNavigationItem
- [x] deleteSurcharge #5937 @trojanh 
- [x] echo #5941 @trojanh 
- [x] enablePaymentMethodForShop @trojanh 
- [x] generateSitemaps #5994  @willopez 
- [x] inviteShopMember #5975 @willopez 
- [x] publishNavigationChanges #5968 @trojanh 
- [x] recalculateReservedSimpleInventory #6005 
- [x] removeAccountAddressBookEntry #5956 @trojanh 
- [x] removeAccountEmailRecord #5954 @trojanh 
- [x] removeAccountFromGroup implemented [here](https://github.com/reactioncommerce/reaction/blob/release-3.0.0/tests/integration/api/mutations/removeAccountFromGroup/removeAccountFromGroup.test.js#L6:L6)
- [x] removeAccountGroup #5946
- [x] removeNavigationItem #5886
- [x] removeTag
- [x] setAccountProfileCurrency #5953 @trojanh 
- [x] setAccountProfileLanguage #5952 @trojanh 
- [x] setTagHeroMedia #5996
- [x] updateAccountAddressBookEntry #5955 @trojanh 
- [x] updateFlatRateFulfillmentMethod #5963 @trojanh 
- [x] updateFlatRateFulfillmentRestriction #5981
- [x] updateGlobalSettings #5950
- [x] updateAccountGroup #5947
- [x] updateNavigationItem #5886
- [x] updateNavigationTree #5914 @trojanh 
- [x] updateShop
- [x] updateShopSettings #5971 
- [x] updateSurcharge #5923 @trojanh 
- [x] updateTag #5875 

### Queries That Have Integration Tests
- account
- administrators
- catalogItemProduct
- catalogItems
- group
- groups
- primaryShopId
- productsByTagId
- shop
- simpleInventory
- tags
- viewer

### Queries That Need Integration Tests
- [x] accountCartByAccountId #5855 
- [x] addressValidation #5915
- [x] addressValidationServices #5929 
- [x] anonymousCartByCartId #5858
- [x] availablePaymentMethods #5860
- [x] getFlatRateFulfillmentRestriction #5868
- [x] getFlatRateFulfillmentRestrictions #5865
- [x] globalSettings #5870
- [x] navigationItemsByShopId - #5706
- [x] navigationTreeById - #5706
- [x] orderById - #5373
- [x] orderByReferenceId - #5689 
- [x] ordersByAccountId - #5690 
- [x] paymentMethods #5880
- [x] ping - PR #5326
- [x] primaryShop - #5374
- [x] roles #5884
- [x] shopBySlug - #5375
- [x] shopSettings #5872
- [x] sitemap #5887
- [x] surchargeById #5893
- [x] surcharges #5901 
- [x] systemInformation #5905
- [x] tag - #5867
- [x] taxCodes #5908
- [x] taxServices #5909

### Other tests needed
- [x] full add to cart and checkout flow - issue #5518

## How

If you want to help with this effort:
1. Pick a mutation or query. Ensure that there isn't already an issue created in this epic for it.
2. Create an individual GitHub issue to track that one test.
    - Title: "Add Integration Test for [NAME HERE] GraphQL [PICK ONE: mutation/query]"
    - In the description, just link to this issue.
3. Assign the individual GitHub issue to yourself.
4. Add the issue to this epic in ZenHub.
5. Write any tests you think are necessary to fully test all variations of the query or mutation, including permission checks and any other security concerns you have.
    - [Writing Jest Integration Tests](https://docs.reactioncommerce.com/docs/writing-jest-integration-tests)
    - [Running Jest Integration Tests](https://docs.reactioncommerce.com/docs/running-jest-integration-tests)
6. Submit a PR that resolves the individual GitHub issue. Edit this description and add a link to your PR right after the query or mutation name in the bullet list.
7. After your PR is merged to `develop`, check off that query or mutation in the bullet list in this issue.

**Comment by willopez** [comment]
All tests in this epic have been implemented!
