### ISSUE TITLE
📋 Feature release checklist: Bulk Tag Product

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/reaction#5499]
This is a ticket to track all the issues related to releasing the Bulk Tag Product feature:

## Feature release checklist
- [x] **Remaining PRs**: Tag all in-progress PRs and Issues necessary for this release, so the release managers know about it. Link issues/PRs here: https://github.com/reactioncommerce/reaction/projects/17
- [x] **Test cases:** Create a list of all the test cases, edge cases necessary for a first-time feature release. Post it here in this ticket.
- [x] **E2E Testing matrix:** Make a PR into reaction-docs to update the testing matrix for post-release testing requirements, which should be more high-level than the first-time release cases. PR here: https://github.com/reactioncommerce/reaction-docs/pull/870
- [x] **User Docs:** Make a PR into reaction-docs for user docs that should be ready by release time. **PR in Review**: https://github.com/reactioncommerce/reaction-docs/pull/872
- [x] **Change Log:** Draft language for the Change Log announcement of this feature. @machikoyasuda **PR in Review/Need visual aid**

## Test cases

1. Filtering: A user can upload a CSV of product IDs and see the products checked in that CSV in the UI -
- Test error case with a bad CSV.
- No products were found
- Some products were found and some were not
- All products were found

2. After filtering, clicking X on the Chip should go back to an unfiltered state.
3. Adding tags - After using the CSV filter, a user can bulk add several tags to those products.

Single tag:
- All products had tag added
- No products had tag added (error)
- Some products had tag added and some did not

Multiple tags:
- All products had tags added
- No products had tags added (error)
- Some products had tags added and some did not

4. Removing tags: After using the CSV filter, a user can remove a tag or many tags from many products.

Single tag:
- All products had tag removed
- No products had tag removed (error)
- Some products had tag removed and some did not

Multiple tags:
- All products had tags removed
- No products had tags removed (error)
- Some products had tags removed and some did not

5. A user should be able to manually check 2+ products from the table to add/remove tags. They shouldn't have to go through the CSV file.
6. A user can filter multiple CSVs at once. Upload 2 or 3 CSV files and see if all are filtered.

Load testing: Test with 2 products, 20 products, 50 products CSV.

Find CSV files in Slack.

## Test matrix

Updated: https://docs.reactioncommerce.com/docs/next/testing-matrix

## Changelog copy

---
### Bulk add and remove Tags from Products

Reaction Admin users can now add and remove tags from products in bulk. After selecting multiple products in the product table or filtering products with a CSV file, users can specify tags they'd like to add or remove from those products. 

This feature uses several new components from the [**Catalyst Design System**](https://catalyst.reactioncommerce.com/), including [**SplitButton**](https://catalyst.reactioncommerce.com/#/Components/Actions/SplitButton), [**Chip**](https://catalyst.reactioncommerce.com/#/Components/Content/Chip) and [**MultiSelect**](https://catalyst.reactioncommerce.com/#/Components/Inputs/Select). Several dependencies, including [`react-select`](https://github.com/JedWatson/react-select), [`react-dropzone`](https://github.com/react-dropzone/react-dropzone) and [`material-ui/core`](https://material-ui.com/) were upgraded to their latest versions.

***Include gif*** 

---

**Comment by machikoyasuda** [comment]
@reaction-justin Could you please edit this copy? This copy will be added to the [CHANGELOG](https://github.com/reactioncommerce/reaction/blob/master/CHANGELOG.md) next week when we release this feature. The intended readers are developers, but also, at a high level, all business/design audiences as well. If you want a link to test/play around with the feature, DM me on Slack and I will send you a URL and test CSV files. 

Once released, this information and graphics can be used on social media, newsletters, etc.

We don't have a great place to draft this, so I'm just putting it in GitHub:

---
### Bulk add and remove Tags from Products

Reaction Admin users can now add and remove tags from products in bulk. After selecting multiple products in the product table or filtering products with a CSV file, users can specify tags they'd like to add or remove from those products. This feature uses several new components from the [**Catalyst Design System**](https://catalyst.reactioncommerce.com/), including [**SplitButton**](https://catalyst.reactioncommerce.com/#/Components/Actions/SplitButton), [**Chip**](https://catalyst.reactioncommerce.com/#/Components/Content/Chip) and [**MultiSelect**](https://catalyst.reactioncommerce.com/#/Components/Inputs/Select).

***Include gif*** 
---
