### ISSUE TITLE
GQL: All the things

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#5747]
This is THE epic to get everything that's currently still using meteor methods, pub/sub or otherwise mutating the mongo database directly into GraphQL.

## Big

- [x] #5750 [GQL] Core (core/core) (@mikemurray  or @willopez)
- [x] #5749 [GQL] Catalog (core/catalog) (@mikemurray)

## Smaller efforts

- [x] #5767 [GQL] Stripe settings (included/payments-stripe) (assigned to @willopez)
- [x] #5761 [GQL] Tax Rates (included/taxes-rates) (assigned to @mikemurray)
- [x] #5759 [GQL] Email SMTP (included/email-smtp)} (assigned to @willopez)
- [x] #5758 [GQL] Discount Codes (included/discount-codes) (assigned to @mikemurray)
- [x] #5752 [GQL] Discounts (core/discounts) (delete/merge with Discount Codes) (assigned to @mikemurray)
- [x] #5766 [GQL] Shop settings autoform fields need GQL mutations (core/dashboard/client) (assinged to @willopez)
- [x] #5756 [GQL] Templates (core/templates) (assigned to @trojanh)
- [x] #5754 [GQL] Layout (core/layout) (@willopez )
- [x] #5753 [GQL] Email (core/email) (assigned to @trojanh)
- [x] #5755 [GQL] Tags (core/tags) (assigned to @trojanh)

## Delete?

- [x] #5760 [GQL] Notifications (included/notifications) (@mikemurray)

## Do last

- [x] #5748 [GQL][Last] Accounts (core/accounts) (@mikemurray)
