### ISSUE TITLE
[GQL] Core (core/core)

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#5750]
There are a lot of files in this package. Many methods / pub/sub already have GQL resolvers. Many other things are only for the UI. The Methods and the pub/sub are the best places to start creating new GQL resolvers

### Collections

- [ ] Packages
- [ ] Tags
- [ ] Shops
- [ ] Roles

### Move to `api-utils`

- [ ] Merge deep from `/lib/api`

### Meteor dependencies

- [ ] meteor/alanning:roles
- [ ] meteor/accounts-base
- [ ] meteor/check
- [ ] meteor/meteor (getting user `Meteor.user()`)

**Likely in support of the front-end app**
- [ ] meteor/ddp-client
- [ ] meteor/webapp
- [ ] meteor/ongoworks:security
- [ ] meteor/alanning:roles
- [ ] meteor/ddp-rate-limiter

### Methods

- [x] shop/updateShopExternalServices **seems like a method for an autoform** (use env vars or setting api) (maybe removed, make sure!!!)
- [x] package/update **used by many packages to update their settings** (use env vars or setting api)
- [x] registry/update **updated the registry entries in Package document** (use env vars or setting api)

Update Shop
- [x] shop/updateBrandAssets (add generic update to updateShop mutation) #5846
- [x] shop/updateDefaultParcelSize (add to updateShop mutation) #5846
- [x] shop/updateCurrencyConfiguration
- [x] shop/updateLanguageConfiguration

**Has an equivalent GQL API, or is unnecessary**
- [x] shop/createTag **available in tag api, no need to convert**
- [x] shop/updateHeaderTags **use tag GQL API. this is to manage tag hierarchy, which we don't support**
- [x] shop/togglePackage **enable/disables a package**
- [x] shop/locateAddress **address validation**

### Publications

- [x] product.js #5818
- [x] products.js **`ProductsAdminList` pub is likely the only one need to be converted, the others are unused** #5818
- [x] shipping.js #5844
- [x] packages.js (stop relying on it, then delete)
- [x] email.js (gets email jobs. should be part of email package: #5753)

**We think we already have these, verify that we do!**
- [x] accounts.js (verify these queries exist in API) #5848
- [x] members.js (verify that shop administrators GQL query meets the requirement for this pub)
- [x] media.js (dont need to convert, make sure the places that load images still work with removal)

**Has an equivalent GQL API, or is unnecessary**

- [x] groups.js
- [x] orders.js
- [x] cart.js
- [x] themes.js
- [x] counts.js (shop counts)
- [x] tags.js
- [x] shops.js
- [x] reactiveAggregate.js
- [x] ServiceConfiguration (google/fb/twitter login config secrets) **(probably just delete/ dont convert)**

### File structure
```
├── client
│   └── util
│       └── getOpaqueIds.js
└── server
    ├── Reaction
    │   ├── absoluteUrl.js
    │   ├── accountUtils.js
    │   ├── core.js
    │   ├── getSlug.js
    │   ├── importer.js
    │   ├── index.js
    │   ├── loadSettings.js
    │   └── setDomain.js
    ├── index.js
    ├── methods
    │   ├── getOpaqueIdFromInternalId.js
    │   ├── index.js
    │   ├── shop
    │   │   ├── createTag.js
    │   │   ├── index.js
    │   │   ├── locateAddress.js
    │   │   ├── togglePackage.js
    │   │   ├── updateBrandAssets.js
    │   │   ├── updateCurrencyConfiguration.js
    │   │   ├── updateDefaultParcelSize.js
    │   │   ├── updateHeaderTags.js
    │   │   ├── updateLanguageConfiguration.js
    │   │   └── updateShopExternalServices.js
    │   ├── updatePackage.js
    │   └── updateRegistry.js
    ├── publications
    │   ├── accounts
    │   │   └── serviceConfiguration.js
    │   ├── collections
    │   │   ├── accounts.js
    │   │   ├── cart.js
    │   │   ├── groups.js
    │   │   ├── media.js
    │   │   ├── members.js
    │   │   ├── orders.js
    │   │   ├── packages.js
    │   │   ├── product.js
    │   │   ├── products.js
    │   │   ├── reactiveAggregate.js
    │   │   ├── shipping.js
    │   │   ├── shops.js
    │   │   ├── tags.js
    │   │   └── themes.js
    │   ├── counts.js
    │   ├── email.js
    │   └── index.js
    ├── startup
    │   ├── browser-policy.js
    │   ├── collection-security.js
    │   ├── index.js
    │   └── rate-limits.js
    └── util
        ├── connectionDataStore.js
        ├── formatPhoneNumber.js
        └── geocoder.js
```
