### ISSUE TITLE
CartWorkflow improvement

### ISSUE THREAD

**Issue by newsiberian** [reactioncommerce/reaction#592]
Hello. There is a few moments, that we could improve in `cartWorkflow`.

We can have a situation where a user deletes products from `cart`, being in the last `cartWorkflow` stage and if he later put in a `cart` other products, then entering the `checkout`, it will be the last `cartWorkflow` stage. I think this is not expected. I believe, much more logical way will be to throw him back to the third `coreCheckoutShipping` step.

It may also be a situations where a user who is at any stage beyond the second `checkoutAddressBook` address may cancel the `defaultShippingAddress` or he could remove all addresses at all. Currently, when this happens, nothing has changed, as far as I understand.
Maybe if we have changes at second stage we need to react on it somehow?

#### Tasks

- [x] When you select a shipping address, we should reset the following steps and recalculate shipping rates.
- [x] With the first address entered, both shipping and address should be selected by default (and set isDefault).

UPD: ready, but need tests
- [x] if quantity changes, we reset to coreCheckoutShipping, but use the isDefault shipping address.

**Comment by aaronjudd** [comment]
Your interpretation of how it should work is correct. There is an outstanding issue https://github.com/reactioncommerce/reaction/issues/250 that covers this. The shipping needs to be recalculated, and the previously completed workflow should be reset `coreCheckoutShipping`.

**Comment by newsiberian** [comment]
I want to say even more, we should reset shipping when `isShippingDefault` address was changed.

I was thinking about bug/feature in #585 and now I think this is right behave. If user already filled `isShippingDefault` address in Profile or during the previous order, it is fine that he may start with `coreCheckoutShipping`. Right?

**Comment by aaronjudd** [comment]
See my comments about the feature/bug - it's really two things:
1 ) When you select a shipping address, we should reset the following steps and recalculate shipping rates.
2)  With the first address entered, both shipping and address should be selected by default.
3) if quantity changes, we reset to `coreCheckoutShipping`, but use the `isDefault` shipping address.

**Comment by newsiberian** [comment]
@aaronjudd, hello, I'm looking into shipping now and do not quite understand what do you mean by saying "recalculate shipping rates" in item 1. As I can see, we have a flat rates only. What need to be recalculated?

**Comment by aaronjudd** [comment]
We are building additional shipping packages, such as Shippo, and support for FedEx,etc..

**Comment by aaronjudd** [comment]
I've updated #250 description with more details on shipping rate recalculation timing.

**Comment by aaronjudd** [comment]
I believe this main intent of this ticket is now covered and closed by discussion in #250. (and the other updates @newsiberian made).
