### ISSUE TITLE
[EPIC] Move all plugins into their own npm packages

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#6107]
We'd like to move all our internal plugins into their own `npm` packages that can be installed in Reaction.

I have created plugin repositories for all of the plugins listed below. They are currently all set to `private`, unless the work on them has already been completed. Our goal is to move these plugins to all use `Apache` licensing, however, I've created all of the repositories using `GPL`, as that is the current licensing of the code that's being transferred from the core API. There are instructions as to how to re-license if allowed in the "How to convert a repository" doc.

We'd love for community help to move this process along. If you'd like to help out, please DM @kieckhafer in Gitter, and let me know which plugin you'd like to move, and I'll make that repository public and help you get started with a set of instructions.

### DONE

- [x] accounts  
    **Repository**: https://github.com/reactioncommerce/api-plugin-accounts 
    **Ticket**: #6166 
    **Plugin PR**: https://github.com/reactioncommerce/api-plugin-accounts/pull/1
    **Reaction PR**: #6189

- [x] address-validation (previously address)
    **Repository**: https://github.com/reactioncommerce/api-plugin-address-validation
    **Ticket**: #6167
    **Plugin PR**: https://github.com/reactioncommerce/api-plugin-address-validation/pull/1
    **Reaction PR**: #6186

- [x] address-validation-test
    **Repository**: https://github.com/reactioncommerce/api-plugin-address-validation-test
    **Ticket**: #6121 
    **Plugin PR**: https://github.com/reactioncommerce/api-plugin-address-validation-test/pull/1
    **Reaction PR**: #6186

- [x] carts
    **Repository**: https://github.com/reactioncommerce/api-plugin-carts
    **Ticket**: #6168
    **Plugin PR**: https://github.com/reactioncommerce/api-plugin-carts/pull/3
    **Reaction PR**: #6215

- [x] catalogs
    **Repository**: https://github.com/reactioncommerce/api-plugin-catalogs
    **Ticket**: #6169
    **Plugin PR**: https://github.com/reactioncommerce/api-plugin-catalogs/pull/1
    **Reaction PR**: #6196 

- [x] discounts
    **Repository**: https://github.com/reactioncommerce/api-plugin-discounts
    **Ticket**: #6170
    **Plugin PR**: https://github.com/reactioncommerce/api-plugin-discounts/pull/1
    **Reaction PR**: #6216 

- [x] email
    **Repository**: https://github.com/reactioncommerce/api-plugin-email
    **Ticket**: #6171
    **Plugin PR**: https://github.com/reactioncommerce/api-plugin-email/pull/1
    **Reaction PR**: #6200

- [x] email-smtp  
    **Repository**: https://github.com/reactioncommerce/api-plugin-email-smtp
    **Ticket**: #6124 
    **Plugin PR**: https://github.com/reactioncommerce/api-plugin-email-smtp/pull/1
    **Reaction PR**: #6218

- [x] email-templates  
    **Repository**: https://github.com/reactioncommerce/api-plugin-email-templates
    **Ticket**: #6125 
    **Plugin PR**: https://github.com/reactioncommerce/api-plugin-email-templates/pull/3
    **Plugin PR FIX**: https://github.com/reactioncommerce/api-plugin-email-templates/pull/4
    **Reaction PR**: #6219

- [x] files
    **Repository**: https://github.com/reactioncommerce/api-plugin-files
    **Ticket**: #6172
    **Plugin PR**: https://github.com/reactioncommerce/api-plugin-files/pull/1
    **Reaction PR**: https://github.com/reactioncommerce/reaction/pull/6217

- [x] i18n
    **Repository**: https://github.com/reactioncommerce/api-plugin-i18n
    **Ticket**: #6173
    **Plugin PR**: https://github.com/reactioncommerce/api-plugin-i18n/pull/1
    **Reaction PR**: #6193 

- [x] inventory
    **Repository**: https://github.com/reactioncommerce/api-plugin-inventory
    **Ticket**: #6174
    **Plugin PR**: https://github.com/reactioncommerce/api-plugin-inventory/pull/1
    **Reaction PR**: https://github.com/reactioncommerce/reaction/pull/6226

- [x] inventory-simple  
    **Repository**: https://github.com/reactioncommerce/api-plugin-inventory-simple
    **Ticket**: #6133 
    **Plugin PR**: https://github.com/reactioncommerce/api-plugin-inventory-simple/pull/1
    **Reaction PR**: https://github.com/reactioncommerce/reaction/pull/6222

- [x] job-queue
    **Repository**: https://github.com/reactioncommerce/api-plugin-job-queue
    **Ticket**: #6126 
    **Plugin PR**: https://github.com/reactioncommerce/api-plugin-job-queue/pull/1
    **Reaction PR**: #6197 

- [x] notifications  
    **Repository**: https://github.com/reactioncommerce/api-plugin-notifications
    **Ticket**: #6128 
    **Plugin PR**: https://github.com/reactioncommerce/api-plugin-notifications/pull/1
    **Reaction PR**: #6211

- [x] orders
    **Repository**: https://github.com/reactioncommerce/api-plugin-orders
    **Ticket**: #6175
    **Plugin PR**: https://github.com/reactioncommerce/api-plugin-orders/pull/4
    **Reaction PR**: #6214

- [x] payments
    **Repository**: https://github.com/reactioncommerce/api-plugin-payments
    **Ticket**: #6176
    **Plugin PR**: https://github.com/reactioncommerce/api-plugin-payments/pull/3
    **Reaction PR**: #6221

- [x] payments-stripe
    **Repository**: https://github.com/reactioncommerce/api-plugin-payments-stripe
    **Ticket**: #6130 
    **Plugin PR**: https://github.com/reactioncommerce/api-plugin-payments-stripe/pull/1
    **Reaction PR**: #6161 

- [x] pricing-simple 
    **Repository**: https://github.com/reactioncommerce/api-plugin-pricing-simple
    **Ticket**: #6134 
    **Plugin PR**: https://github.com/reactioncommerce/api-plugin-pricing-simple/pull/1
    **Reaction PR**: https://github.com/reactioncommerce/reaction/pull/6225/

- [x] products
    **Repository**: https://github.com/reactioncommerce/api-plugin-products
    **Ticket**: #6177
    **Plugin PR**: https://github.com/reactioncommerce/api-plugin-products/pull/1
    **Reaction PR**: https://github.com/reactioncommerce/reaction/pull/6220

- [x] settings
    **Repository**: https://github.com/reactioncommerce/api-plugin-settings
    **Ticket**: #6178
    **Plugin PR**: https://github.com/reactioncommerce/api-plugin-settings/pull/1
    **Reaction PR**: #6203

- [x] shipments (previously shipping)
    **Repository**: https://github.com/reactioncommerce/api-plugin-shipments
    **Ticket**: #6179
    **Plugin PR**: https://github.com/reactioncommerce/api-plugin-shipments/pull/1
    **Reaction PR**: #6224 

- [x] shipments-flat-rate (previously shipping-rates)  
    **Repository**: https://github.com/reactioncommerce/api-plugin-shipments-flat-rate
    **Ticket**: #6131 
    **Plugin PR**: https://github.com/reactioncommerce/api-plugin-shipments-flat-rate/pull/1
    **Reaction PR**: #6199 

- [x] shops
    **Repository**: https://github.com/reactioncommerce/api-plugin-shops
    **Ticket**: #6180
    **Plugin PR**: https://github.com/reactioncommerce/api-plugin-shops/pull/3
    **Reaction PR**: #6201

- [x] simple-schema
    **Repository**: https://github.com/reactioncommerce/api-plugin-simple-schema 
    **Ticket**: #6135 
    **Plugin PR**: https://github.com/reactioncommerce/api-plugin-simple-schema/pull/1
    **Reaction PR**: #6202 

- [x] surcharges
    **Repository**: https://github.com/reactioncommerce/api-plugin-surcharges
    **Ticket**: #6137 
    **Plugin PR**: https://github.com/reactioncommerce/api-plugin-surcharges/pull/1
    **Reaction PR**: #6223

- [x] tags 
    **Repository**: https://github.com/reactioncommerce/api-plugin-tags
    **Ticket**: #6181
    **Plugin PR**: https://github.com/reactioncommerce/api-plugin-tags/pull/1
    **Reaction PR**: #6212 

- [x] taxes
    **Repository**: https://github.com/reactioncommerce/api-plugin-taxes
    **Ticket**: #6182
    **Plugin PR**: https://github.com/reactioncommerce/api-plugin-taxes/pull/1
    **Reaction PR**: https://github.com/reactioncommerce/reaction/pull/6228

- [x] taxes-flat-rate (previously taxes-rates)  
    **Repository**: https://github.com/reactioncommerce/api-plugin-taxes-flat-rate 
    **Ticket**: #6139 
    **Plugin PR**: https://github.com/reactioncommerce/api-plugin-taxes-flat-rate/pull/1
    **Reaction PR**: #6198 

### DONE (renaming complete)

- [x] authentication  
    **Repository**: https://github.com/reactioncommerce/plugin-authentication
    **Ticket**: #6122   
    **Plugin PR**: n/a
    **Reaction PR**: #6108
     **TODO**: Update plugin to include `api` prefix in name https://github.com/reactioncommerce/plugin-authentication/issues/1

- [x] discount-codes  
    **Repository**: https://github.com/reactioncommerce/plugin-discount-codes
    **Ticket**: #6123 
    **Plugin PR**: n/a
    **Reaction PR**: #6157 
    **TODO**: Update plugin to include `api` prefix in name https://github.com/reactioncommerce/plugin-discount-codes/issues/1

- [x] navigation
    **Repository**: https://github.com/reactioncommerce/plugin-navigation  
    **Ticket**: #6127 
    **Plugin PR**: https://github.com/reactioncommerce/plugin-navigation/pull/1
    **Reaction PR**: #6118
     **TODO**: Update plugin to include `api` prefix in name https://github.com/reactioncommerce/plugin-navigation/issues/3

- [x] payments-example
    **Repository**: https://github.com/reactioncommerce/plugin-payments-example
    **Ticket**: #6129 
    **Plugin PR**: https://github.com/reactioncommerce/plugin-payments-example/pull/2
    **Reaction PR**: #6142
     **TODO**: Update plugin to include `api` prefix in name https://github.com/reactioncommerce/plugin-payments-example/issues/3

- [x] simple-authorization  
    **Repository**: https://github.com/reactioncommerce/plugin-simple-authorization 
    **Ticket**: #6132  
    **Plugin PR**: https://github.com/reactioncommerce/plugin-simple-authorization/pull/1
    **Reaction PR**: #6110
     **TODO**: Update plugin to include `api` prefix in name https://github.com/reactioncommerce/plugin-simple-authorization/issues/10

- [x] sitemap-generator
    **Repository**: https://github.com/reactioncommerce/plugin-sitemap-generator  
    **Ticket**: #6136 
    **Plugin PR**: https://github.com/reactioncommerce/plugin-sitemap-generator/pull/1
    **Reaction PR**: #6144
     **TODO**: Update plugin to include `api` prefix in name https://github.com/reactioncommerce/plugin-sitemap-generator/issues/4

- [x] system-info  
    **Repository**: https://github.com/reactioncommerce/plugin-system-info  
    **Ticket**: #6140 
    **Plugin PR**: https://github.com/reactioncommerce/plugin-system-information/pull/1
    **Reaction PR**: #6105
     **TODO**: Update plugin to include `api` prefix in name https://github.com/reactioncommerce/plugin-system-information/issues/3

- [x] translations
    **Repository**: https://github.com/reactioncommerce/plugin-translations  
    **Ticket**: #6138 
    **Plugin PR**: https://github.com/reactioncommerce/plugin-translations/pull/1
    **Reaction PR**: #6160 
     **TODO**: Update plugin to include `api` prefix in name https://github.com/reactioncommerce/plugin-translations/issues/3

**Comment by kieckhafer** [comment]
All plugins have been moved! There are a few remaining tickets in the [Project board](https://github.com/orgs/reactioncommerce/projects/9#card-33980042), but this EPIC can be closed!
